### ISSUE TITLE
Add an automated test

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-MotionToSingleJusticeAppeals#25]
Use the [Kiln](https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/automated_integrated_testing) framework to add at least one automated test to this repository

**Comment by omarpinangoh** [comment]
It wont allow me to download the Json file.

**Comment by nonprofittechy** [comment]
I'll download the JSON file for you

**Comment by nonprofittechy** [comment]
[interview (1).json](https://github.com/SuffolkLITLab/docassemble-MotionToSingleJusticeAppeals/files/14644159/interview.1.json)
